### ISSUE TITLE
Current state.

### ISSUE THREAD

**Issue by juliolitwin** [HeatXD/PleaseResync#1]
Hey guys,

I'm following the project and I'm finding it incredible!

- How is development progressing?
- Is there a TODO List?
- Is there any means of communication? (ex. disagree)
- Are you using Godot or Unity for the tests?
- Does rollback support more than 2 players? 

Cheers!

**Comment by JonathanPicques** [comment]
Hi there :)

> How is development progressing?

The project is fairly new (1 week) but the development is going well

> Is there a TODO List?

We are working towards having a more modern C# GGPO replacement with these features:
- Better API
- Custom network
- Supporting multiple players per device (a device is like a computer, or console: this means local coop with other remote players)

> Is there any means of communication? (ex. disagree)

For the time being, the library is programmed by @HeatXD and I, and we will keep it as-is for the foreseeable future

> Are you using Godot or Unity for the tests?

PleaseResync is a C# library, so you will be able to use it in both :)
Personally I will use with for my upcoming Godot game

> Does rollback support more than 2 players?

Yes :) and also support multiple players on the same device (local coop with other remote players)

**Comment by juliolitwin** [comment]
It's amazing! :)

A question, regarding the network structure, will it be client<->client (P2P), server<->client or even both?

I understand, it would be nice to have a communication channel, for discussions, showcase and others.

Would there be any possibility of a future showcase (video gameplay)?

**Comment by HeatXD** [comment]
Hello!,

> A question, regarding the network structure, will it be client<->client (P2P), server<->client or even both?

Both games of @JonathanPicques  and I are P2P games hence the network structure will be mainly tailored towards P2P. 
This doesnt mean a server<>client structure wont work with some modifications.

> Would there be any possibility of a future showcase (video gameplay)?

We will make example projects using various C# supported frameworks / game engines showing the library in action.
Whenever the library is ready to use in production!
